// <auto-generated />
using GameVault.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameVault.Migrations
    {
    [DbContext(typeof(GameVaultDbContext))]
    partial class GameVaultDbContextModelSnapshot : ModelSnapshot
        {
        protected override void BuildModel(ModelBuilder modelBuilder)
            {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameVault.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                            {
                            Id = 1,
                            Genre = "Adventure",
                            ReleaseYear = 1986,
                            Title = "The Legend of Zelda"
                            },
                        new
                            {
                            Id = 2,
                            Genre = "Platformer",
                            ReleaseYear = 1985,
                            Title = "Super Mario Bros"
                            },
                        new
                            {
                            Id = 3,
                            Genre = "Sandbox",
                            ReleaseYear = 2011,
                            Title = "Minecraft"
                            },
                        new
                            {
                            Id = 4,
                            Genre = "RPG",
                            ReleaseYear = 2015,
                            Title = "The Witcher 3"
                            },
                        new
                            {
                            Id = 5,
                            Genre = "Puzzle",
                            ReleaseYear = 2011,
                            Title = "Portal 2"
                            });
                });
#pragma warning restore 612, 618
            }
        }
    }
